from ai_data_analyst.ingestion.loader import load_csv
from ai_data_analyst.sql.database import create_database
from ai_data_analyst.sql.executor import execute_sql
from ai_data_analyst.sql.validator import validate_sql


# Load dataset
df = load_csv("data/raw/sales.csv")


# Create database
engine = create_database(df)


# SQL generated by the LLM
sql = """
SELECT
    region,
    SUM(sales) AS total_sales
FROM dataset
GROUP BY region
ORDER BY total_sales DESC
LIMIT 1;
"""


# Validate SQL
if not validate_sql(sql):
    raise ValueError("Unsafe SQL query!")


# Execute SQL
result = execute_sql(engine, sql)


print("\n========== SQL RESULT ==========\n")
print(result)